name: Test Carthage Integration

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - master
    - develop
    - improve-ci

env:
  PROJECT_NAME: TempProject

defaults:
  run:
    shell: bash

jobs:
  pre-building_carthages:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: n1hility/cancel-previous-runs@v2
      with:
        token: ${{ secrets.MANUAL_ACTION_TOKEN }}
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Resolve dependencies
      run: |
        brew upgrade carthage

    - name: Fetching Carthages
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir $PROJECT_NAME && cd $PROJECT_NAME
        CWD=$(pwd)
        CURRENT_COMMIT=$(git rev-parse HEAD)
        echo "git \"file://$CWD/../\" \"$CURRENT_COMMIT\"" > Cartfile
        ../Scripts/carthage.sh update --use-xcframeworks
        ls -ln

    - name: Archive Carthages
      uses: actions/upload-artifact@v3
      with:
        name: carthage
        path: ${{ env.PROJECT_NAME }}/Carthage


  carthage-test:
    runs-on: macos-12
    needs: pre-building_carthages
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/download-artifact@v3
      with:
        name: carthage
        path: ${{ env.PROJECT_NAME }}/Carthage

    - name: Resolve dependencies
      run: |
        ls -ln
        brew install xcodegen

    - name: Setup test fixture
      run: |
        Scripts/generate_xcodegen_project.sh carthage -w -c -p $PROJECT_NAME

    - name: Build and Test
      working-directory: ${{ env.PROJECT_NAME }}
      env:
        APP_NAME: ${{ env.PROJECT_NAME }}_App
      run: |
        xcodebuild clean build test -scheme $APP_NAME -destination 'name=iPhone 13' | xcpretty --utf --color


  carthage-archive:
    runs-on: macos-12
    needs: pre-building_carthages
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/download-artifact@v3
      with:
        name: carthage
        path: ${{ env.PROJECT_NAME }}/Carthage

    - name: Setup test fixture
      run: |
        Scripts/generate_swift_project.sh carthage -w -c -p $PROJECT_NAME

    - name: Build and Archive for generic iOS device
      working-directory: ${{ env.PROJECT_NAME }}
      run: |
        xcodebuild clean build archive -scheme $PROJECT_NAME -destination 'generic/platform=iOS' | xcpretty --utf --color

    - name: Build and Archive for x86_64 simulator
      working-directory: ${{ env.PROJECT_NAME }}
      run: |
        xcodebuild clean build archive -scheme $PROJECT_NAME -destination 'generic/platform=iOS Simulator' | xcpretty --utf --color
